global:
  scrape_interval: 1s  # スクレイプの間隔を1秒に設定

# アラートルールファイルを読み込むためのセクションを追加
rule_files:
  - "rules/*.yml"  # rulesディレクトリ内の全ての.ymlファイルを読み込む

scrape_configs:
  - job_name: 'bybit_xrp_usdt_exporter'
    static_configs:
      - targets: ['python-app:8000']  # カスタムエクスポーターのアドレス
